### ISSUE TITLE
rmd lacks the orginal ggplot2 code

### ISSUE THREAD

**Issue by philbowsher** [AlekFisher/bug-free-octo-spork#3]
hey - noticed we cleaned up the ggplot2 code

 ad_treatment %>%
 filter(age >= 81L & age <= 85L) %>%
 filter(mmse >= 15 & mmse <= 
    28.8) %>%
 ggplot() +
 aes(x = age, group = health_status) +
 geom_histogram(bins = 30L, fill = "#0c4c8a") +
 theme_minimal()

**Comment by AlekFisher** [comment]
We'll check it out

**Comment by philbowsher** [comment]
thats all you need ot do!
